name: Periodic Workflow

on:
  schedule:
    - cron: '* * * * *' # Run the workflow every minute

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Current Time
        run: echo "The current time is $(date)"
